[package]
name = "yew-life"
version = "0.1.0"
edition = "2021"
authors = ["fmstat <stateresa.fm@gmail.com>"]

[dependencies]
getrandom = { version = "0.2.12", features = ["js"] }
gloo = "0.11.0"
log = "0.4.21"
rand = "0.8.5"
wasm-logger = "0.2.0"
yew = { version = "0.21.0", features = ["csr"] }
